test: prod

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.10.53.252:3306/numble?serverTimezone=Asia/Seoul
    username: root
    password: ${DATASOURCE_PASSWORD}
    initialization-mode: always

  sql:
    init:
      mode: never