test: dev
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/numble?serverTimezone=Asia/Seoul
    username: root
    password: root
    initialization-mode: always

  sql:
    init:
      mode: always